### ISSUE TITLE
Launch Guide?

### ISSUE THREAD

**Issue by mattysweeps** [juanjp600/scpcb#101]
I imported into visual studio but I get a segmentation fault when running a build.
Debugging also fails with the error message: `blitz3D.lib is not a valid Win32 application`

There's a ticket #67 for updating the wiki, but a quick guide in the readme would suffice.

Many thanks!

**Comment by CommanderMark** [comment]
Sounds like you're trying to compile and run the B3D runtime instead of the game itself.

Right click the "SCPCB" project in the solution explorer and select "Set as Startup Project."

**Comment by mattysweeps** [comment]
That helped! I can debug now, but now I fail at https://github.com/juanjp600/scpcb/blob/cbn/Src/GameMain.cpp#L1158

```
SCPCB.exe!blitz3d_open() Line 1883
	at c:\users\m0pt0\src\scpcb\libraries\bbruntime\bbblitz3d.cpp(1883)
[Inline Frame] SCPCB.exe!CBN::Graphics3DExt(int) Line 1158
	at c:\users\m0pt0\src\scpcb\src\gamemain.cpp(1158)
SCPCB.exe!CBN::Launcher::Launcher() Line 33
	at c:\users\m0pt0\src\scpcb\src\menus\launcher.cpp(33)
SCPCB.exe!CBN::updateGameState() Line 508
	at c:\users\m0pt0\src\scpcb\src\gamemain.cpp(508)
SCPCB.exe!CBN::EntryPoint() Line 164
	at c:\users\m0pt0\src\scpcb\src\gamemain.cpp(164)
SCPCB.exe!main() Line 52
	at c:\users\m0pt0\src\scpcb\src\main.cpp(52)
```

Due to line 525 of bbblitz3d.cpp returning false:
```
if( dirDraw->QueryInterface( IID_IDirect3D7,(void**)&dir3d )>=0 )
```

I must not have a system dependency installed. Looks directx related?
Thanks again!

**Comment by CommanderMark** [comment]
Are you compiling for 64-bit?

On the topbar next to the launch button, change "x64" to "x86" in the dropdown menu.

**Comment by mattysweeps** [comment]
Ah, that did the trick.

How do you feel about adding something like this to the readme?

```
## Visual Studio Instructions

- Set SCPCB as the Startup Project
- Target the Windows SDK to `10.0.17763.0`
- Set the solution platform to Win32
```
