### ISSUE TITLE
SCP-1048-A, broken

### ISSUE THREAD

**Issue by Goldenschmidt** [juanjp600/scpcb#105]
Heya!

I found an issue in the game. 
As the title mentions, the Teddy Bear of Ears (Also known as SCP-1048-A), is broken.
Okay, maybe not broken in general. But.. I guess I did something, to make it break.

Short explanation:
I'm able to move all the way up to it, without it triggering, and attacking me, even though I've almost basically been standing right where it's standing.

Detailed explanation: 
I started a new game, and already 2-3 rooms in, I encounter this SCP.
At first, I thought it was the normal teddy bear, the SCP-1048. But right as I get past it, it begins to move, and I immediately tries to get away. I got scared, because this was literally the first time I encounter SCP-1048-A. At least, in the corridors.
So.. Yeah.. I die by turning into ears.
Okay. I then respawn, and I head back to where SCP-1048-A was, and it's just standing there, looking at me. So I decided to go the other way instead. Funny enough, I encounter SCP-1048-A again that way, after at least 7 corridors from start position.
I look up on wiki how to get past it, and I manage to do it by immediately running back from where I was. It worked, and SCP-1048-A was gone. Okay. Good. On this other side, I encounter the room where the two scientists gets killed down at the bottom of the stairs, by SCP-173.
And so on, and so on..
I then walk all the way back to the first corridor, and heads over to where I first encountered SCP-1048-A, and wouldn't ya know it, it's still standing there. So... I try the same procedure, just to figure out... .... nothing happens, when you get close. I looked like a fool, getting close, and almost instantly jumping back, to start running.
So... It's standing there... but... it's not doing anything. Not even looking at me, as I walk past it.

I'm using a Windows 10 pc, in case you need this info

If you need more information, feel free to ask me.
![Screenshot_1 SCP-1048-A](https://user-images.githubusercontent.com/23004163/63644225-1e9d9e00-c6e4-11e9-973b-f6915e2e7cdc.png)

**Comment by juanjp600** [comment]
Not relevant to v1.4
