### ISSUE TITLE
How do I open

### ISSUE THREAD

**Issue by A-Random-Birb** [juanjp600/scpcb#106]
I'm special and want to know how to open the game

**Comment by juanjp600** [comment]
At the moment there's not really much to open at all (most of our progress so far has been on implementing tech, if you run the current repo you will see nothing but a pink screen), but if you really do want to check this out in its current state, you will need Visual Studio 2019 or the latest version of XCode, depending on the platform you're on.

If you're wondering how to open v1.3.11, this is not really the place to ask; you could try asking for assistance with that at https://discord.gg/undertow or https://undertowgames.com/forum/viewforum.php?f=6
